name: Java CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      LMNTAL_HOME: ${{ github.workspace }}
      slim_CHECK_ND: "yes"
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get -qq update
    - run: sudo apt-get install -y ant re2c
    - run: ant
    - run: git clone https://github.com/lmntal/slim.git
    - run: cd slim
    - run: ./autogen.sh
    - run: ./configure
    - run: make -j
    - run: make -j check
