name: Java CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      LMNTAL_HOME: ${{ github.workspace }}
      slim_CHECK_ND: "yes"
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt -qq update
    - run: sudo apt install -y ant re2c
    - run: ant
    - uses: actions/checkout@v2
      with:
        repository: lmntal/slim
        path: slim
        token: ${{ secrets.EX_GITHUB_TOKEN }}
    - run: cd slim
    - run: ./autogen.sh
    - run: ./configure
    - run: make -j
    - run: make -j check
